Library/Controllers/LibrarianController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Library.Controllers
{
    [Authorize(Policy = "RequireEmail")]
    [Authorize(Roles = "Administrator")]
    public class LibrarianController : Controller
    {
        private LibraryContext _context;

        public LibrarianController(LibraryContext libraryContext)
        {
            _context = libraryContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddBook()
        {
            PopulateGenerDropDownList();
            return View();
        }

        [HttpPost, ActionName("AddBook")]
        [ValidateAntiForgeryToken]
        public IActionResult AddBookPost(Book book)
        {
            if (ModelState.IsValid)
            {
                if (book.PhotoAvatar != null && book.PhotoAvatar.Length > 0)
                {
                    book.ImageMimeType = book.PhotoAvatar.ContentType;
                    book.ImageName = Path.GetFileName(book.PhotoAvatar.FileName);
                    using (var memoryStream = new MemoryStream())
                    {
                        book.PhotoAvatar.CopyTo(memoryStream);
                        book.PhotoFile = memoryStream.ToArray();
                    }
                    book.Available = true;
                    _context.Add(book);
                    _context.SaveChanges();
                }
                return RedirectToAction(nameof(ThankYou));
            }
            PopulateGenerDropDownList(book.Genre.Id);
            return View();
        }

        public IActionResult ThankYou()
        {
            return View();
        }

        private void PopulateGenerDropDownList(int? selectedGener = null)
        {
            var genres = from b in _context.Genres
                        orderby b.Name
                        select b;

            ViewBag.GenerList = new SelectList(genres.AsNoTracking(), "Id", "Name", selectedGener);
        }
    }
}

Library/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Library.Data;
using Library.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;


namespace Library.Controllers
{
    public class LibraryController : Controller
    {

        private LibraryContext _context;
        private IHostingEnvironment _environment;

        public LibraryController(LibraryContext libraryContext, IHostingEnvironment environment)
        {
            _context = libraryContext;
            _environment = environment;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var booksQuery = from b in _context.Books
                             where b.Recommended == true
                             orderby b.Author
                             select b;

            return View(booksQuery);
        }

        [Authorize]
        public IActionResult GetBooksByGener()
        {
            var booksGenerQuery = from b in _context.Books
                                  orderby b.Genre.Name
                                  select b;

            return View(booksGenerQuery);
        }

        public IActionResult LendingBook(int id)
        {
            Book book = _context.Books.FirstOrDefault(b => b.Id == id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost, ActionName("LendingBook")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LendingBookPost(int id)
        {
            var bookToUpdate = _context.Books.FirstOrDefault(b => b.Id == id);
            bookToUpdate.Available = false;
            if (await TryUpdateModelAsync<Book>(
                bookToUpdate,
                "",
                b => b.Available))
            {
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(bookToUpdate);
        }

        public IActionResult GetImage(int id)
        {
            Book requestedBook = _context.Books.FirstOrDefault(b => b.Id == id);
            if (requestedBook != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedBook.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedBook.ImageMimeType);
                }
                else
                {
                    if (requestedBook.PhotoFile.Length > 0)
                    {
                        return File(requestedBook.PhotoFile, requestedBook.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
    }
}

Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/library-style.css" rel="stylesheet" />
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/popper.js/dist/umd/popper.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom p-1">
        <div class="collapse navbar-collapse" id="nav-content">
			<ul class="navbar-nav" id="nav-content">
				<li class="nav-item">
					<a class="nav-link" href="@Url.Action("Index", "Library")">Library<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="@Url.Action("GetBooksByGener", "Library")">Our Books</a>
				</li>

				@if (User.IsInRole("Administrator"))
				{
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index", "Librarian")">Workers Portal</a>
					</li>
				}
				@if (User.Identity.IsAuthenticated)
				{
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Logout", "Account")">Logout</a>
					</li>
				}
				else
				{
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Login", "Account")">Login</a>
					</li>
				}
			</ul>
        </div>
    </nav>
    <h1 class="main-title">Welcome to Our Library</h1>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>